language: php

php:
  - 5.4

env:
  global:
    - DRUSH_VERSION=5.8.0
    - SAUCE_USERNAME=myplanet-skeletor
    # SAUCE_ACCESS_KEY
    - secure: "FegBL7IVCVSvOBg0rGwUqL+Lci9kT9xLI/yDMOqjE1J4C9cpSSzhz9pEe/w0\n1GHgGZOkPYwRHl28qGqxvF6oOoiX3dLS1xO39c89GPNwY1GPuCF6Sv3ySAm4\nD86FRhxuJmSDkYfucIYVMwmTWxNY+DoSDnBtnbPLSFXFCh+cXCM="
  matrix:
    - SAUCE_BROWSER=googlechrome
    - SAUCE_BROWSER=firefox
    - SAUCE_BROWSER=iexplore

before_install: tmp/scripts/travis_before_install.sh

before_script:
  - tmp/scripts/travis_install.sh
  - $TRAVIS_SECURE_ENV_VAR && curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash

notifications:
  email: false

script: tmp/scripts/travis_test.sh
